CREATE TABLE [dbo].[DIA]
(
[ID_DIA] [int] NOT NULL IDENTITY(1, 1),
[ID_MEDICO] [int] NULL,
[NOMBRE_DIA] [varchar] (10) COLLATE Modern_Spanish_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DIA] ADD CONSTRAINT [PK_DIA] PRIMARY KEY NONCLUSTERED  ([ID_DIA]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [RELATIONSHIP_18_FK] ON [dbo].[DIA] ([ID_MEDICO]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DIA] ADD CONSTRAINT [FK_DIA_RELATIONS_MEDICO] FOREIGN KEY ([ID_MEDICO]) REFERENCES [dbo].[MEDICO] ([ID_MEDICO])
GO
