CREATE TABLE [dbo].[PACIENTE]
(
[ID_PACIENTE] [int] NOT NULL IDENTITY(1, 1),
[NOMBRES_PACIENTE] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[APELLIDOS_PACIENTE] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CEDULA_PACIENTE] [varchar] (10) COLLATE Modern_Spanish_CI_AS NOT NULL,
[TELEFONO_PACIENTE] [varchar] (10) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CORREO_PACIENTE] [varchar] (30) COLLATE Modern_Spanish_CI_AS NOT NULL,
[DIRECCION_PACIENTE] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PACIENTE] ADD CONSTRAINT [PK_PACIENTE] PRIMARY KEY NONCLUSTERED  ([ID_PACIENTE]) ON [PRIMARY]
GO
