CREATE TABLE [dbo].[CLINICA]
(
[ID_CLINICA] [int] NOT NULL IDENTITY(1, 1),
[ID_ADMINISTRADOR] [int] NULL,
[NOMBRE_CLINICA] [varchar] (20) COLLATE Modern_Spanish_CI_AS NOT NULL,
[TELEFONO_CLINICA] [varchar] (10) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CORREO_CLINICA] [varchar] (30) COLLATE Modern_Spanish_CI_AS NOT NULL,
[DIRECCION_CLINICA] [varchar] (50) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLINICA] ADD CONSTRAINT [PK_CLINICA] PRIMARY KEY NONCLUSTERED  ([ID_CLINICA]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [RELATIONSHIP_16_FK] ON [dbo].[CLINICA] ([ID_ADMINISTRADOR]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLINICA] ADD CONSTRAINT [FK_CLINICA_RELATIONS_ADMINIST] FOREIGN KEY ([ID_ADMINISTRADOR]) REFERENCES [dbo].[ADMINISTRADOR] ([ID_ADMINISTRADOR])
GO
