CREATE TABLE [dbo].[HORA]
(
[ID_HORA] [int] NOT NULL IDENTITY(1, 1),
[ID_DIA] [int] NULL,
[HORA_INICIAL] [datetime] NOT NULL,
[HORA_FINAL] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[HORA] ADD CONSTRAINT [PK_HORA] PRIMARY KEY NONCLUSTERED  ([ID_HORA]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [RELATIONSHIP_17_FK] ON [dbo].[HORA] ([ID_DIA]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[HORA] ADD CONSTRAINT [FK_HORA_RELATIONS_DIA] FOREIGN KEY ([ID_DIA]) REFERENCES [dbo].[DIA] ([ID_DIA])
GO
