CREATE TABLE [dbo].[CITA]
(
[ID_CITA] [int] NOT NULL IDENTITY(1, 1),
[ID_PACIENTE] [int] NULL,
[ID_RECEPCIONISTA] [int] NULL,
[ID_MEDICO] [int] NULL,
[FECHA_CITA] [datetime] NOT NULL,
[HORA_CITA] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CITA] ADD CONSTRAINT [PK_CITA] PRIMARY KEY NONCLUSTERED  ([ID_CITA]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [RELATIONSHIP_2_FK] ON [dbo].[CITA] ([ID_MEDICO]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [RELATIONSHIP_3_FK] ON [dbo].[CITA] ([ID_PACIENTE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [RELATIONSHIP_6_FK] ON [dbo].[CITA] ([ID_RECEPCIONISTA]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CITA] ADD CONSTRAINT [FK_CITA_RELATIONS_MEDICO] FOREIGN KEY ([ID_MEDICO]) REFERENCES [dbo].[MEDICO] ([ID_MEDICO])
GO
ALTER TABLE [dbo].[CITA] ADD CONSTRAINT [FK_CITA_RELATIONS_PACIENTE] FOREIGN KEY ([ID_PACIENTE]) REFERENCES [dbo].[PACIENTE] ([ID_PACIENTE])
GO
ALTER TABLE [dbo].[CITA] ADD CONSTRAINT [FK_CITA_RELATIONS_RECEPCIO] FOREIGN KEY ([ID_RECEPCIONISTA]) REFERENCES [dbo].[RECEPCIONISTA] ([ID_RECEPCIONISTA])
GO
