CREATE TABLE [dbo].[RECEPCIONISTA]
(
[ID_RECEPCIONISTA] [int] NOT NULL IDENTITY(1, 1),
[ID_PERFIL] [int] NULL,
[NOMBRES_RECEPCINISTA] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[APELLIDOS_RECEPCIONISTA] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CEDULA_RECEPCIONISTA] [varchar] (10) COLLATE Modern_Spanish_CI_AS NOT NULL,
[TELEFONO_RECEPCIONISTA] [varchar] (10) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CORREO_RECEPCIONISTA] [varchar] (30) COLLATE Modern_Spanish_CI_AS NOT NULL,
[DIRECCION_RECEPCIONISTA] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RECEPCIONISTA] ADD CONSTRAINT [PK_RECEPCIONISTA] PRIMARY KEY NONCLUSTERED  ([ID_RECEPCIONISTA]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [RELATIONSHIP_12_FK] ON [dbo].[RECEPCIONISTA] ([ID_PERFIL]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RECEPCIONISTA] ADD CONSTRAINT [FK_RECEPCIO_RELATIONS_PERFIL] FOREIGN KEY ([ID_PERFIL]) REFERENCES [dbo].[PERFIL] ([ID_PERFIL])
GO
