CREATE TABLE [dbo].[USUARIO]
(
[ID_USUARIO] [int] NOT NULL IDENTITY(1, 1),
[ID_PERFIL] [int] NULL,
[NOMBRE_USUARIO] [varchar] (20) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CONTRASENA_USUARIO] [varchar] (10) COLLATE Modern_Spanish_CI_AS NOT NULL,
[ROL_USUARIO] [varchar] (15) COLLATE Modern_Spanish_CI_AS NOT NULL,
[ESTADO_USUARIO] [bit] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[USUARIO] ADD CONSTRAINT [PK_USUARIO] PRIMARY KEY NONCLUSTERED  ([ID_USUARIO]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [RELATIONSHIP_7_FK] ON [dbo].[USUARIO] ([ID_PERFIL]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[USUARIO] ADD CONSTRAINT [FK_USUARIO_RELATIONS_PERFIL] FOREIGN KEY ([ID_PERFIL]) REFERENCES [dbo].[PERFIL] ([ID_PERFIL])
GO
