CREATE TABLE [dbo].[CONSULTA]
(
[ID_CONSULTA] [int] NOT NULL IDENTITY(1, 1),
[ID_CITA] [int] NULL,
[DESCRIPCION_CONSULTA] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[DIAGNOSTICO] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[RECETA] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[TRATAMIENTO] [bit] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONSULTA] ADD CONSTRAINT [PK_CONSULTA] PRIMARY KEY NONCLUSTERED  ([ID_CONSULTA]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [RELATIONSHIP_5_FK] ON [dbo].[CONSULTA] ([ID_CITA]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CONSULTA] ADD CONSTRAINT [FK_CONSULTA_RELATIONS_CITA] FOREIGN KEY ([ID_CITA]) REFERENCES [dbo].[CITA] ([ID_CITA])
GO
