CREATE TABLE [dbo].[PERFIL]
(
[ID_PERFIL] [int] NOT NULL IDENTITY(1, 1),
[ID_RECEPCIONISTA] [int] NULL,
[ID_MEDICO] [int] NULL,
[ID_USUARIO] [int] NULL,
[ID_ADMINISTRADOR] [int] NULL,
[FOTO] [image] NOT NULL,
[COLOR] [varchar] (10) COLLATE Modern_Spanish_CI_AS NOT NULL,
[LETRA] [varchar] (30) COLLATE Modern_Spanish_CI_AS NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[PERFIL] ADD CONSTRAINT [PK_PERFIL] PRIMARY KEY NONCLUSTERED  ([ID_PERFIL]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [RELATIONSHIP_13_FK] ON [dbo].[PERFIL] ([ID_ADMINISTRADOR]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [RELATIONSHIP_9_FK] ON [dbo].[PERFIL] ([ID_MEDICO]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [RELATIONSHIP_11_FK] ON [dbo].[PERFIL] ([ID_RECEPCIONISTA]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [RELATIONSHIP_8_FK] ON [dbo].[PERFIL] ([ID_USUARIO]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PERFIL] ADD CONSTRAINT [FK_PERFIL_RELATIONS_ADMINIST] FOREIGN KEY ([ID_ADMINISTRADOR]) REFERENCES [dbo].[ADMINISTRADOR] ([ID_ADMINISTRADOR])
GO
ALTER TABLE [dbo].[PERFIL] ADD CONSTRAINT [FK_PERFIL_RELATIONS_MEDICO] FOREIGN KEY ([ID_MEDICO]) REFERENCES [dbo].[MEDICO] ([ID_MEDICO])
GO
ALTER TABLE [dbo].[PERFIL] ADD CONSTRAINT [FK_PERFIL_RELATIONS_RECEPCIO] FOREIGN KEY ([ID_RECEPCIONISTA]) REFERENCES [dbo].[RECEPCIONISTA] ([ID_RECEPCIONISTA])
GO
ALTER TABLE [dbo].[PERFIL] ADD CONSTRAINT [FK_PERFIL_RELATIONS_USUARIO] FOREIGN KEY ([ID_USUARIO]) REFERENCES [dbo].[USUARIO] ([ID_USUARIO])
GO
