CREATE TABLE [dbo].[ADMINISTRADOR]
(
[ID_ADMINISTRADOR] [int] NOT NULL IDENTITY(1, 1),
[ID_CLINICA] [int] NULL,
[ID_PERFIL] [int] NULL,
[NOMBRES_ADMINISTRADOR] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[APELLIDOS_ADMINISTRADOR] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CEDULA_ADMINISTRADOR] [varchar] (10) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CORREO_ADMINISTRADOR] [varchar] (30) COLLATE Modern_Spanish_CI_AS NOT NULL,
[DIRECCION_ADMINISTRADOR] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ADMINISTRADOR] ADD CONSTRAINT [PK_ADMINISTRADOR] PRIMARY KEY NONCLUSTERED  ([ID_ADMINISTRADOR]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [RELATIONSHIP_15_FK] ON [dbo].[ADMINISTRADOR] ([ID_CLINICA]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [RELATIONSHIP_14_FK] ON [dbo].[ADMINISTRADOR] ([ID_PERFIL]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ADMINISTRADOR] ADD CONSTRAINT [FK_ADMINIST_RELATIONS_CLINICA] FOREIGN KEY ([ID_CLINICA]) REFERENCES [dbo].[CLINICA] ([ID_CLINICA])
GO
ALTER TABLE [dbo].[ADMINISTRADOR] ADD CONSTRAINT [FK_ADMINIST_RELATIONS_PERFIL] FOREIGN KEY ([ID_PERFIL]) REFERENCES [dbo].[PERFIL] ([ID_PERFIL])
GO
