CREATE TABLE [dbo].[ESPECIALIDAD]
(
[ID_ESPECIALIDAD] [int] NOT NULL IDENTITY(1, 1),
[NOMBRE_ESPECIALIDAD] [varchar] (20) COLLATE Modern_Spanish_CI_AS NOT NULL,
[DESCRIPCION_ESPECIALIDAD] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ESPECIALIDAD] ADD CONSTRAINT [PK_ESPECIALIDAD] PRIMARY KEY NONCLUSTERED  ([ID_ESPECIALIDAD]) ON [PRIMARY]
GO
