CREATE TABLE [dbo].[MEDICO]
(
[ID_MEDICO] [int] NOT NULL IDENTITY(1, 1),
[ID_PERFIL] [int] NULL,
[ID_ESPECIALIDAD] [int] NULL,
[NOMBRES_MEDICO] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[APELLIDOS_MEDICO] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CEDULA_MEDICO] [varchar] (10) COLLATE Modern_Spanish_CI_AS NOT NULL,
[TELEFONO_MEDICO] [varchar] (10) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CORREO_MEDICO] [varchar] (30) COLLATE Modern_Spanish_CI_AS NOT NULL,
[DIRECCION_MEDICO] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MEDICO] ADD CONSTRAINT [PK_MEDICO] PRIMARY KEY NONCLUSTERED  ([ID_MEDICO]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [RELATIONSHIP_1_FK] ON [dbo].[MEDICO] ([ID_ESPECIALIDAD]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [RELATIONSHIP_10_FK] ON [dbo].[MEDICO] ([ID_PERFIL]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MEDICO] ADD CONSTRAINT [FK_MEDICO_RELATIONS_ESPECIAL] FOREIGN KEY ([ID_ESPECIALIDAD]) REFERENCES [dbo].[ESPECIALIDAD] ([ID_ESPECIALIDAD])
GO
ALTER TABLE [dbo].[MEDICO] ADD CONSTRAINT [FK_MEDICO_RELATIONS_PERFIL] FOREIGN KEY ([ID_PERFIL]) REFERENCES [dbo].[PERFIL] ([ID_PERFIL])
GO
